### ISSUE TITLE
How to show the "Help" floating button

### ISSUE THREAD

**Issue by luanfonceca** [CrossLead/angular-zendesk-widget#12]
Hi folks, i just installed this package to use in my angular app.
I followed the README to setup the `angular-zendesk-widget` and its working just fine. But i need to show that zendesk "Help" button, i created a link on my html to call the `ZendeskWidget.activate()` function on my controller and its working.

There are any configuration that i miss in order to show up that floating button with the layout of zendesk.

Thanks in advance.

**Comment by yangchristian** [comment]
@luanfonceca can you show how you're instantiating and configuring the widget? By default, you should get the floating version of the widget unless you're, say, calling `zE.hide()` in the `beforePageLoad` callback. If you're verbatim following the instructions under [Settings](https://github.com/CrossLead/angular-zendesk-widget#settings) in the README, you should remove the callback.

**Comment by yangchristian** [comment]
Closing due to inaction.
