### ISSUE TITLE
angular2

### ISSUE THREAD

**Issue by siddharthrathi** [CrossLead/angular-zendesk-widget#13]
how to implement in angular2 framework ?

Is it provide support for angular2 framework ?

**Comment by mustafa-qamaruddin** [comment]
does it work in Angular 2?

**Comment by yangchristian** [comment]
We currently don't have Angular 2 support planned, but feel free to make a fork or PR.

**Comment by AlisonVilela** [comment]
I made a new component for Angular 4+ based in this component
[ngx-zendesk-webwidget](https://github.com/AlisonVilela/ngx-zendesk-webwidget)

**Comment by yangchristian** [comment]
Added link in README via 64633ab3b5a015004bfc34be904b7952c3c0f6cc
