### ISSUE TITLE
setHelpCenterSuggestions only work during ZendeskWidgetProvider config

### ISSUE THREAD

**Issue by rbinsztock** [CrossLead/angular-zendesk-widget#15]
Hi guys,

I try to update the Help center suggestion when user access to specific route page, sadly the setHelpCenterSuggestions work only during initialization 

```
beforePageLoad : function(zE) {
      zE.setLocale('fr');
      zE.setHelpCenterSuggestions({ url : true });
      zE.setHelpCenterSuggestions({ search : 'boost' });
      zE.hide();
 }
```

If I try to update the help center suggestion inside my controller component via :
`ZendeskWidget.setHelpCenterSuggestions({ search : 'boost' });`

Did I missed something ?

Angular 1.6.4

**Comment by jovana** [comment]
Hay @rbinsztock, Did you solve this already?

I have added this to  $rootScope.$on('$stateChangeSuccess', function(){});
This is working!

Good luck!
